### ISSUE TITLE
EXTENSION: most recent pic not showing up first

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/NewsPix#24]

**Comment by jayvachon** [comment]
I might be a little confused on what the desired behavior is here, but I've changed it so that stories are shown in the reverse order in which they were added (so the most recently added story will be "first"). That said -- the user is just cycling through a list of stories & won't see the new stories until the loop has completed and they return to the top of the story list.

unless the idea is that any time an admin adds a new story the loop should reset on the client side & users will see the story that was just added on their next new tab. to me this seems like a lot of added work on the client side & I'm not sure what the benefit is -- people tend to open new tabs frequently

**Comment by kanarinka** [comment]
Yes - I think that's the desired behavior - that the most recently added
story is "first" on the list. No need to make the client for automatically
updating the loop for the moment. I agree with your assessment.

**Comment by jayvachon** [comment]
cool! gonna close this - feel free to reopen if anyone has a different idea on how to order stories

**Comment by jayvachon** [comment]
also i should note that you'll have to update the db on the server with a new field for each story called "position". this is just an int that keeps track of the order in which stories were added (first story added = 0)

**Comment by kanarinka** [comment]
Ok should be fine - the nice thing about noSQL is that it should just
update when the first value gets put in. But if there's an error I'll know
where to track it down
